# Note: a "disabled" dict can have arbitrary named properties
# with lists of disabled tests as a value. Those properties' names
# are for humans only and are there only to explain
# why a group of tests is disabled.

tests:
  - base_unittests:
      disabled:
        upstream_failures:
          - FilePathTest.FromUTF8Unsafe_And_AsUTF8Unsafe
          - RTLTest.WrapPathWithLTRFormatting
          - SysStrings.SysNativeMBAndWide
          - SysStrings.SysNativeMBToWide
          - SysStrings.SysWideToNativeMB
        to_fix:
          - PartitionReallocReturnNullTest.RepeatedReturnNullDirect
          - WeakPtrDeathTest*
  - cc_unittests
  - cc_blink_unittests
  - content_unittests:
      disabled:
        upstream_failures:
          - BackgroundSyncManagerTest.*
          - FrameServiceBaseTest.ConnectionError
          - MediaSessionControllerTest.*
          - MediaStreamUIProxyFeaturePolicyTest.FeaturePolicy
          - PresentationServiceImplTest.*
        to_fix:
          - _/DOMStorageMapParamTest.EnforcesQuota/0
          - _/DOMStorageMapParamTest.EnforcesQuota/1
          - RenderFrameAudioInputStreamFactoryTest.ConstructDestruct
  - crypto_unittests
  - device_unittests
  - gin_unittests
  - gpu_unittests
  - ipc_tests
  - media_unittests
  - capture_unittests
  - midi_unittests
  - media_mojo_unittests
  - mojo_unittests
  - mojo_common_unittests
  - net_unittests:
      disabled:
        upstream_failures:
          - EndToEndTestsWithTls/EndToEndTestWithTls.SimpleRequestResponsev6/*
          - FilenameUtilTest.GenerateFileName
          - SSLClientSocketTest.*
          - UDPSocketTest.ClientGetLocalPeerAddresses
          - UDPSocketTest.ClientSetDoNotFragment
  - ppapi_unittests
  - printing_unittests
  - skia_unittests
  - sql_unittests
  - storage_unittests
  - gn_unittests
  - ui_base_unittests
  - compositor_unittests
  - display_unittests
  - events_unittests
  - gl_unittests
  - url_unittests
  - url_ipc_unittests
  # V8
  - unittests:
      disabled:
        upstream_failures:
          - LiveRangeUnitTest.InvalidConstruction
          - LiveRangeUnitTest.SplinterMultipleIntervalsInside
          - LiveRangeUnitTest.SplitInvalidStart
  # Blink
  - blink_common_unittests
  - blink_heap_unittests
  - blink_platform_unittests:
      disabled:
        # TODO(alexeykuzmin): Should those be fixed?
        - AnimatedPNGTests.*
        - AnimatedWebPTests.*
        - AnimatedWEBPTests.clearCacheExceptFrameWithAncestors
        - BitmapImageTest.*
        - BMPImageDecoderTest*
        - DecodedImageOrientationHistogramTest*
        - DecodedImageTypeHistogramTest*
        - DeferredImageDecoderTest.decodeOnOtherThread
        - DeferredImageDecoderTestWoPlatform*
        - GIFImageDecoderTest*
        - HighContrastImageClassifierTest*
        - ICOImageDecoderTests*
        - JPEGImageDecoderTest*
        - FilePathConversionTest*
        - PaintPropertyNodeTest.InitialStateAndReset
        - PNGTests*
        - StaticPNGTests*
        - StaticWebPTests*
  - webkit_unit_tests:
      disabled:
        upstream_failures:
          - Document/ThreadableLoaderTest.CancelAfterStart/0
          - ModernMediaControlsImplTest.ControlsShouldUseSafeAreaInsets
          - ScriptRunnerTest.QueueReentrantScript_InOrder
          - ScrollbarsTestWithVirtualTimer.PressScrollbarButtonOnInfiniteScrolling
          - VirtualTimeTest.AllowVirtualTimeToAdvance
          - VirtualTimeTest.VirtualTimeNotAllowedToAdvanceWhileResourcesLoading
  - wtf_unittests
  # Third party
  - angle_unittests
  - env_chromium_unittests
# TODO(alexeykuzmin): Should be run somehow differently.
#  - disk_cache_memory_test:
#      platform: linux
  - sandbox_linux_unittests:
      platform: linux
      disabled:
        upstream_failures:
          - BrokerProcess.OpenFilePermsWithClientCheck
          - BrokerProcess.OpenFilePermsWithClientCheckNoEnt
          - BrokerProcess.OpenOpenFilePermsNoClientCheck
          - BrokerProcess.OpenOpenFilePermsNoClientCheckNoEnt
          - SandboxBPF.SigBus
  - dbus_unittests:
      platform: linux
      disabled:
        upstream_failures:
          - EndToEndAsyncTest.InvalidServiceName
          - EndToEndSyncTest.InvalidServiceName
          - MessageTest.SetInvalidHeaders
