name: Issue Labeled

on:
  issues:
    types: [labeled]

jobs:
  issue-labeled:
    runs-on: ubuntu-latest
    steps:
      - name: blocked/need-repro
        if: github.event.label.name == 'blocked/need-repro'
        uses: actions-cool/issues-helper@dad28fdb88da5f082c04659b7373d85790f9b135 # v3.3.0
        with:
          actions: 'create-comment'
          body: |
            Hello @${{ github.event.issue.user.login }}. Thanks for reporting this and helping to make Electron better!

            Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

            Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests. 

            Now adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.
  
